use_frameworks!
platform :ios, '8.0'
target 'CDChatList_Example' do
    
    pod 'CDChatList', :path => '../'
    pod 'SDWebImage/GIF',:inhibit_warnings => true
    pod 'FLAnimatedImage',:inhibit_warnings => true
    pod 'GDPerformanceView', '~> 1.3.1'
    pod 'Toast'
    target 'CDChatList_Tests' do
        inherit! :search_paths
        
        
    end
end
