use_frameworks!


target 'CDChatList_Example' do
  pod 'CDChatList', :path => '../'
  pod 'SDWebImage'
  pod 'CDLabel', '~> 0.0.11', :source => 'http://git-ma.paic.com.cn/aat/AATComponent_iOS.git'
end